### ISSUE TITLE
dtparam and dtoverlay

### ISSUE THREAD

**Issue by mihaelaapetroaie** [advancedtelematic/meta-updater-raspberrypi#23]
I've been trying to enable SPI and i2c on the Raspberry Pi 3. I'm on the rocko branch on an Ubuntu 16.04 machine.

When not using meta-updater I'd simply append the following to `config.txt` in the boot partition:

    dtparam=spi=on
    dtparam=i2c_arm=on
    dtparam=i2c1=on

Reading on the raspberry pi documentation I figured that the firmware reads `config.txt`, does some more steps, runs of the `start.elf` files which will create a Device Tree that is passed to the kernel.

Now with meta-updater and meta-updater-raspberrypi, the device tree doesn't get passed to the kernel, but to u-boot. And then u-boot would need to pass it forward to the kernel. But here's the problem. The firmware won't create the device tree since all the `.dtb` and `.dtbo` files are flatten in the fitImage that is in the second partition. So the whole `dtparams=` and `dtoverlays=` gets ignored, at least in my experience.

For overlays, I can add the ones I want to the `KERNEL_DEVICETREE` and `KERNEL_DEVICETREE_raspberrypi3_sota` variables. If I mount the second partition produced and `mkimage -l vmlinuz` I can see that the new overlays are there. However, if I inspect the device tree (with `dtc -I fs /proc/device-tree`) on the running device, the overlays are actually ignored.

I found no solution for easily setting`dtparam`s but to create an overlay, which as said, doesn't work.

I'm temporarily overcoming this by patching the kernel `arch/arm/boot/dts/bcm283x.dtsi` and changing the default values to the ones I need and copy-paste extra overlays.

Is there a better way to do those things?

**Comment by Jmennius** [comment]
Hi @mihaelaapetroaie , yes there is a better way to do it.
Instead of relying on overlays (which are loaded and applied dynamically) or patching the source, what you should do is create your own device tree source (dts), based on RPi one (e.g. `bcm2710-rpi-3-b.dts`). 
Of course, you don't have to rewrite the `bcm2710-rpi-3-b.dts` - only include it in your dts:
```
/* My custom RPi based board */

#include "bcm2710-rpi-3-b.dts"

/* Enable I2C bus 1 */
&i2c1 {
	status = "okay";

	/* We have EEPROM with address 0x51 on the bus */
	eeprom: m24c01@51 {
		compatible = "at24,24c01";
		reg = <0x51>;
		pagesize = <16>;
	};
};
```
You'll find nice articles (usage and reference) covering device-tree on elinux.org.

**Comment by mirzak** [comment]
Had similar problems with overlays since the change to FIT images. More info at https://at.projects.genivi.org/jira/browse/GDP-796.

But based on your comment above, this is a feature of meta-updater-raspberrypi.

**Comment by Jmennius** [comment]
Hi @mirzak, yes, you can think about this a feature since libostree/meta-updater is unable to handle stuff in RPi FAT32 boot partition and (IMO) RPi style overlays don't make sense in production (RPi has expansion slot and Raspbian is targeted on hobbyists vs fixed purpose production devices).

Overlays are useful for development and if you want to use them you have several options:
- apply them with u-boot (similar to RPi); you can do this manually from cmdline or automatically with script
- apply dynamically, Linux supports this

**Comment by mirzak** [comment]
@Jmennius , totally on-board :).

**Comment by patrickvacek** [comment]
Is this still causing a problem, or can we consider this resolved?

**Comment by mirzak** [comment]
I am good with closing this.

**Comment by KarlEaves** [comment]
I'm experiencing the same problems with overlays.  I have tried patching u-boot to change the fdt_addr_r and scriptaddr variables in the rpi.h config file to no avail. I set the fdt_addr_r in uEnv.txt to the same address that was set in the config file and the fdt still did not load correctly. I have also tried patching the dst file for the kernel directly and that didn't work either. What am I missing here?

**Comment by lbonn** [comment]
@KarlEaves changing `fdt_addr_r` shouldn't have any effect as we are not using it in our boot scripts.

You can have a look at the [main u-boot script](https://github.com/advancedtelematic/meta-updater-raspberrypi/blob/master/recipes-bsp/u-boot-otascript/u-boot-otascript/uEnv.txt) and can modify it to work with external dtbs, like it used to do (see [this commit](https://github.com/advancedtelematic/meta-updater-raspberrypi/commit/94b315d8f69db0c10aee1fcb8626480c4d8626bd#diff-78fef36ec3b869195ae26bda23a037ca)).

We've started using FIT so that ostree can handle dtb and initramfs updates along with the kernel, as they are often coupled. But in recent versions, there are other ways to do it I believe. This meta-updater issue can be of interest: https://github.com/advancedtelematic/meta-updater/issues/320

**Comment by KarlEaves** [comment]
I have tried to edit  ```uEnv.txt``` according to the commit that you referenced but on boot I get ```libfdt fdt_check_header(): FDT_ERR_BADMAGIC```. What other changes should I be making on order to get u-boot to work?

**Comment by lbonn** [comment]
@KarlEaves sorry, this is probably quite a late answer but we include overlays in fit images and call bootm with the configured overlays we want to boot with: https://github.com/Xilinx/u-boot-xlnx/blob/adf5dca97ce1e7fae83419a0cdc3a92e1e93f231/doc/uImage.FIT/overlay-fdt-boot.txt#L203. The way we pass these to u-boot while being able to update that by ostree is through this recipe: https://github.com/advancedtelematic/meta-updater/blob/master/recipes-sota/fit-conf/fit-conf.bb

Apart from that, the fact that dtparam and dtoverlay in config.txt are ignored, is still an ongoing issue. We don't really have a better solution than what @Jmennius suggested, right now: to just write your own overlays or complete dts instead.

But we should probably document this limitation and explain workarounds in the documentation somewhere.

**Comment by lbonn** [comment]
Closing this issue, since we've added an entry in the repo's README: https://github.com/advancedtelematic/meta-updater-raspberrypi#device-tree-configuration
